Fixes error where app module cannot be imported
When calling `module()` with `inject()`, an error is thrown:
```
Error: [$injector:modulerr] Failed to instantiate module ng due to:
TypeError: 'undefined' is not an object (evaluating
'Function.prototype.bind.apply')
```

PhantomJS is not amongst Karma's officially supported browsers.
In 1.x, `Function.prototype.bind` isn't defined. Instead of polyfilling,
or using Phantom 2.x, it is better to stick with supported browsers.

(In addition, TravisCI has been reconfigured to run Chrome.)

READ MORE:
http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/